### ISSUE TITLE
Cannot debug demo app on chrome

### ISSUE THREAD

**Issue by andrea-spotsoftware** [anjmao/ang-select#1]
Hey @anjmao ,
thank you for your work.
I'm following this repository because i'm also interested in building an angular library with webpack.

Just a question, are you able to debug your sources when you run the demo? 
I can put breakpoints, but they are not hitting.

Ciao!

**Comment by anjmao** [comment]
Hey @andrea-spotsoftware, yes, I can debug original Typescript files in Chrome, are you using command `npm run serve-demo` ?

**Comment by andrea-spotsoftware** [comment]
yes, this is the behavior:

![image](https://user-images.githubusercontent.com/6683228/28371788-31e95ff0-6c9e-11e7-9e2c-5d9d3c03a804.png)

**Comment by anjmao** [comment]
Open event is triggered then you open dropdown with keyboard. Try adding break point on toggle method and you should see break point hit.
